version = 0.1
[default.deploy.parameters]
stack_name = "cloud9"
resolve_s3 = true
s3_prefix = "cloud9"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "EnvironmentName=\"ClaimsAppCloud9Environment\" InstanceType=\"t3.small\" ImageId=\"amazonlinux-2023-x86_64\" gitRepo=\"https://github.com/aniloncloud/bedrock-claude-chat\""
image_repositories = []
