AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >

  Stack for managing claims-app resources

Resources:

  AmazonVerifiedPermissions:
    Type: AWS::Serverless::Application
    Properties:
      Location: 001_avp/template.yaml
      
  CognitoUserPool:
    Type: AWS::Serverless::Application
    Properties:
      Location: 002_cognito/template.yaml
      
  BedrockAgentStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: 003_bedrock-agent/template.yaml      
      Parameters:      
        PolicyStoreId: !GetAtt AmazonVerifiedPermissions.Outputs.PolicyStoreId
        UserPoolId: !GetAtt CognitoUserPool.Outputs.UserPoolId
      
  ApiGatewayStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: 004_apigateway/template.yaml      
      Parameters:
        CognitoUserPoolArn: !GetAtt CognitoUserPool.Outputs.UserPoolArn   
        BedrockAgentAliasId: !GetAtt BedrockAgentStack.Outputs.BedrockAgentAliasId
        BedrockAgentId: !GetAtt BedrockAgentStack.Outputs.BedrockAgentId
        
  Cloud9Stack:
    Type: AWS::Serverless::Application
    Properties:
      Location: 005_Cloud9/template.yaml    