version = 0.1
[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = "bedrockLayerArn=\"arn:aws:lambda:us-east-1:742809942259:layer:bedrock-layer:2\""
image_repositories = []
